<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6f26e6c2-0d50-47b5-b492-9065a7380b9e</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);Client\**\*</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Coflnet.Core" Version="0.7.3" />
    <PackageReference Include="Coflnet.Payments.Client" Version="0.22.0" />
    <PackageReference Include="Coflnet.Sky.Api.Client" Version="0.7.6" />
    <PackageReference Include="Coflnet.Sky.Chat.Client" Version="1.0.1" />
    <PackageReference Include="Coflnet.Sky.McConnect" Version="0.5.0" />
    <PackageReference Include="Coflnet.Sky.ModCommands.Client" Version="0.10.1" />
    <PackageReference Include="Coflnet.Sky.PlayerName.Client" Version="0.2.4" />
    <PackageReference Include="Coflnet.Sky.Settings.Client" Version="0.2.3" />
    <PackageReference Include="Discord.Net" Version="3.20.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.*" />
    <PackageReference Include="Octokit" Version="14.0.0" />
    <PackageReference Include="Octokit.GraphQL" Version="0.4.0-beta" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Configuration\faq.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
